name: Terraform Destroy/Apply

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      environment:
        description: Environment to run agains
        type: choice
        options:
          - dev
          - prod
        default: dev
        required: true
      image_tag:
        description: Docker Image to deploy agains
        type: string
        default: 0.3.14
        required: true
      force:
        description: True to force apply
        required: true
        default: false
        type: boolean

run-name: ${{ format('Destroy {0} to {1}', inputs.image_tag, inputs.environment) }}

permissions:
  contents: read
  pull-requests: write

env:
  # Common Env Variables
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_ACCOUNT: "${{ vars.AWS_ACCOUNT }}"
  AWS_REGION: "${{ vars.AWS_REGION }}"
  STATE_BUCKET: "${{ vars.STATE_BUCKET }}"
  ENVIRONMENT: "${{ inputs.environment }}"
  NICKNAME: strapi
  TF_ROOT_PATH: ${{ github.workspace }}/terraform
  TF_VAR_FILE: ${{ github.workspace }}/terraform/environments/${{ inputs.environment }}.tfvars
  # Terraform Specific Env Variables
  DESIRED_COUNT: "${{ vars.DESIRED_COUNT }}"
  IMAGE: camillehe1992/strapi:${{ inputs.image_tag }}
  # Strapi Specific Env Variables
  APP_KEYS: "${{ secrets.APP_KEYS }}"
  API_TOKEN_SALT: "${{ secrets.API_TOKEN_SALT }}"
  ADMIN_JWT_SECRET: "${{ secrets.ADMIN_JWT_SECRET }}"
  TRANSFER_TOKEN_SALT: "${{ secrets.TRANSFER_TOKEN_SALT }}"
  JWT_SECRET: "${{ secrets.JWT_SECRET }}"
  DATABASE_HOST: "${{ vars.DATABASE_HOST }}"
  DATABASE_USERNAME: "${{ vars.DATABASE_USERNAME }}"
  DATABASE_PASSWORD: "${{ secrets.DATABASE_PASSWORD }}"

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      #this is needed since we are running terraform with read-only permissions
      ARM_SKIP_PROVIDER_REGISTRATION: true
    outputs:
      tfplanExitCode: ${{ steps.tf-plan.outputs.exitcode }}

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of the Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Terraform Init
      - name: Terraform Init
        id: tf-init
        run: make init

      # Generates an execution plan for Terraform
      # An exit code of 0 indicated no changes, 1 a terraform failure, 2 there are pending changes.
      - name: Terraform Plan
        id: tf-plan
        working-directory: ${{ env.TF_ROOT_PATH }}
        run: |
          export exitcode=0
          terraform plan -destroy -var-file $TF_VAR_FILE  \
            -var="aws_region=$AWS_REGION" \
            -var="environment=$ENVIRONMENT" \
            -var="nickname=$NICKNAME" \
            -var="image=$IMAGE" \
            -var="desired_count=$DESIRED_COUNT" \
            -var="app_keys=$APP_KEYS" \
            -var="api_token_salt=$API_TOKEN_SALT" \
            -var="admin_jwt_secret=$ADMIN_JWT_SECRET" \
            -var="transfer_token_salt=$TRANSFER_TOKEN_SALT" \
            -var="jwt_secret=$JWT_SECRET" \
            -var="database_host=$DATABASE_HOST" \
            -var="database_username=$DATABASE_USERNAME" \
            -var="database_password=$DATABASE_PASSWORD" \
            -detailed-exitcode -no-color -out tfplan || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else 
            exit 0
          fi

      # Save plan to artifacts
      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: ${{ env.TF_ROOT_PATH }}/tfplan

      # Create string output of Terraform Plan
      - name: Create String Output
        id: tf-plan-string
        working-directory: ${{ env.TF_ROOT_PATH }}
        run: |
          TERRAFORM_PLAN=$(terraform show -no-color tfplan)

          delimiter="$(openssl rand -hex 8)"
          echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
          echo "## Terraform Plan Output" >> $GITHUB_OUTPUT
          echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo '```terraform' >> $GITHUB_OUTPUT
          echo "$TERRAFORM_PLAN" >> $GITHUB_OUTPUT
          echo '```' >> $GITHUB_OUTPUT
          echo "</details>" >> $GITHUB_OUTPUT
          echo "${delimiter}" >> $GITHUB_OUTPUT

      # Publish Terraform Plan as task summary
      - name: Publish Terraform Plan to Task Summary
        env:
          SUMMARY: ${{ steps.tf-plan-string.outputs.summary }}
        run: |
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

  terraform-apply:
    name: Terraform Apply
    if: ${{ inputs.force == true }} || needs.terraform-plan.outputs.tfplanExitCode == 2
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [terraform-plan]

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v4

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: ${{ env.TF_VERSION }}

      # Download saved plan from artifacts
      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ${{ env.TF_ROOT_PATH }}

      # Terraform Apply
      - name: Terraform Init & Apply
        run: |
          make init
          make apply
